### ISSUE TITLE
cupy.cuda.compiler.CompileException: nvrtc: error: failed to load builtins

### ISSUE THREAD

**Issue by Lvhhhh** [ucbdrive/hd3#3]
ubuntu 16.06 
pytorch 1.01 (try the 0.4.0 still error)
python 3.5
cupy cupy_cuda90-6.0.0-cp35-cp35m-manylinux1_x86_64.whl

i have set 
“export PATH=/usr/local/cuda-9.0/bin:$PATH
export CUDA_PATH=/usr/local/cuda-9.0:$CUDA_PATH
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH”

or using the command "CUDA_PATH=/usr/local/cuda-9.0 pip3 install cupy" to install cupy
the cupy is installed well
but when i "bash script/train.sh"
it occurs:
[2019-05-23 10:16:58,638 INFO train.py line 143 23818] => no checkpoint found at 'path_to_pretrained_model'
Traceback (most recent call last):
  File "/home/lvhao/.local/lib/python3.5/site-packages/cupy/cuda/compiler.py", line 242, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy/cuda/nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR unknown (7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 361, in <module>
    main()
  File "train.py", line 187, in main
    args.batch_size)
  File "train.py", line 236, in train
    output = model(img_list=img_list, label_list=label_list, get_loss=True)
  File "/home/lvhao/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lvhao/.local/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/lvhao/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lvhao/hd3-master/hd3model.py", line 32, in forward
    ms_prob, ms_vect = self.hd3net(torch.cat(img_list, 1))
  File "/home/lvhao/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lvhao/hd3-master/models/hd3net.py", line 168, in forward
    tensorFirst=ref_feat, tensorSecond=tar_feat_corr)
  File "/home/lvhao/hd3-master/models/correlation.py", line 464, in FunctionCorrelation
    return _FunctionCorrelation.apply(tensorFirst, tensorSecond)
  File "/home/lvhao/hd3-master/models/correlation.py", line 328, in forward
    'output': self.rbot0
  File "cupy/util.pyx", line 50, in cupy.util.memoize.decorator.ret
  File "/home/lvhao/hd3-master/models/correlation.py", line 291, in cupy_launch
    return cupy.cuda.compile_with_cache(strKernel).get_function(strFunction)
  File "/home/lvhao/.local/lib/python3.5/site-packages/cupy/cuda/compiler.py", line 136, in compile_with_cache
    base = _preprocess('', options, arch)
  File "/home/lvhao/.local/lib/python3.5/site-packages/cupy/cuda/compiler.py", line 97, in _preprocess
    result = prog.compile(options)
  File "/home/lvhao/.local/lib/python3.5/site-packages/cupy/cuda/compiler.py", line 246, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: nvrtc: error: failed to load builtins

how to solve it?

**Comment by yzcjtr** [comment]
Hello. In the script, ``path_to_pretrained_model`` is just a placeholder and you should pass a true path to this argument. Can you fix this? Then let us see what's still problematic.

**Comment by cloudXia777** [comment]
> ubuntu 16.06
> pytorch 1.01 (try the 0.4.0 still error)
> python 3.5
> cupy cupy_cuda90-6.0.0-cp35-cp35m-manylinux1_x86_64.whl
> 
> i have set
> “export PATH=/usr/local/cuda-9.0/bin:$PATH
> export CUDA_PATH=/usr/local/cuda-9.0:$CUDA_PATH
> export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH”
> 
> or using the command "CUDA_PATH=/usr/local/cuda-9.0 pip3 install cupy" to install cupy
> the cupy is installed well
> but when i "bash script/train.sh"
> it occurs:
> [2019-05-23 10:16:58,638 INFO train.py line 143 23818] => no checkpoint found at 'path_to_pretrained_model'
> Traceback (most recent call last):
> File "/home/lvhao/.local/lib/python3.5/site-packages/cupy/cuda/compiler.py", line 242, in compile
> nvrtc.compileProgram(self.ptr, options)
> File "cupy/cuda/nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
> File "cupy/cuda/nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
> File "cupy/cuda/nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
> cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR unknown (7)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "train.py", line 361, in 
> main()
> File "train.py", line 187, in main
> args.batch_size)
> File "train.py", line 236, in train
> output = model(img_list=img_list, label_list=label_list, get_loss=True)
> File "/home/lvhao/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/lvhao/.local/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
> return self.module(*inputs[0], **kwargs[0])
> File "/home/lvhao/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/lvhao/hd3-master/hd3model.py", line 32, in forward
> ms_prob, ms_vect = self.hd3net(torch.cat(img_list, 1))
> File "/home/lvhao/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/lvhao/hd3-master/models/hd3net.py", line 168, in forward
> tensorFirst=ref_feat, tensorSecond=tar_feat_corr)
> File "/home/lvhao/hd3-master/models/correlation.py", line 464, in FunctionCorrelation
> return _FunctionCorrelation.apply(tensorFirst, tensorSecond)
> File "/home/lvhao/hd3-master/models/correlation.py", line 328, in forward
> 'output': self.rbot0
> File "cupy/util.pyx", line 50, in cupy.util.memoize.decorator.ret
> File "/home/lvhao/hd3-master/models/correlation.py", line 291, in cupy_launch
> return cupy.cuda.compile_with_cache(strKernel).get_function(strFunction)
> File "/home/lvhao/.local/lib/python3.5/site-packages/cupy/cuda/compiler.py", line 136, in compile_with_cache
> base = _preprocess('', options, arch)
> File "/home/lvhao/.local/lib/python3.5/site-packages/cupy/cuda/compiler.py", line 97, in _preprocess
> result = prog.compile(options)
> File "/home/lvhao/.local/lib/python3.5/site-packages/cupy/cuda/compiler.py", line 246, in compile
> raise CompileException(log, self.src, self.name, options)
> cupy.cuda.compiler.CompileException: nvrtc: error: failed to load builtins
> 
> how to solve it?

Have you resolved this error? Cos I have one error same as yours, if you solved it, reply me pls.
